fetch: #namespace

    # Fetch Task Realated parameters
    n_actions: 10 #
    # # # linear.x, linear.y, angular.z, wrist_roll, wrist_flex, forearm_roll, elbow_flex, upperarm_roll, shoulder_lift, shoulder_pan, torso_lift, gripper_close
    n_observations: 1 # An image
    max_iterations: 20

    init_pos: [0.7, 0., 0.42, 0, 1.5707963267948966, 0]

    group_name: "arm" #"arm_with_torso"

    gripper_min_dist: 0.0
    gripper_max_dist: 0.08
    gripper_max_effort: 10.0

    exe_single_group: False
    exe_group_num: 2

env:
    inserted_objs:
        insert_task_block_1: []
        insert_task_block_2: []

    inserted_obj_width: 0.04
    target_region:
        cube1: [[0.547, 0.563], [0.092, 0.104], [0.4, 0.5]]
        cylinder1: [[0.547, 0.563], [-0.104, -0.092], [0.4, 0.5]]

    reached_goal_reward: 50.0
    use_shaping: True

    render: True # Use RGB observations
    merge_simple_states_to_img: True # Expand image with one more dimension of predicates and padded zeros

    predicates:
      inserted:
        is_cube1_pushedTo_block1: ['cube1', 'insert_task_block_1', [0.05, 0.05, 0.05]] # offsets.x and offsets.y are (dim_insert/2)/sqrt(2)
        is_cube1_pushedTo_block2: ['cube1', 'insert_task_block_2', [0.05, 0.05, 0.05]]
        is_cylinder1_pushedTo_block1: ['cylinder1', 'insert_task_block_1', [0.05, 0.05, 0.05]]
        is_cylinder1_pushedTo_block2: ['cylinder1', 'insert_task_block_2', [0.05, 0.05, 0.05]]
      within:
          is_cube1_pushedTo_L1: ['cube1', [[0.37, 0.47], [0.05, 0.15], [0.35, 0.5]]] # offsets.x and offsets.y are (dim_insert/2)/sqrt(2)
          is_cube1_pushedTo_L2: ['cube1', [[0.37, 0.47], [-0.15, -0.05], [0.35, 0.5]]]
          is_cylinder1_pushedTo_L1: ['cylinder1', [[0.37, 0.47], [0.05, 0.15], [0.35, 0.5]]]
          is_cylinder1_pushedTo_L2: ['cylinder1', [[0.37, 0.47], [-0.15, -0.05], [0.35, 0.5]]]
      pushed:
        is_get_cube1: ['cube1']
        is_get_cylinder1: ['cylinder1']

    predicates_list: ["is_get_cube1", "is_get_cylinder1", "is_cube1_pushedTo_block1", "is_cube1_pushedTo_block2", "is_cylinder1_pushedTo_block1", "is_cylinder1_pushedTo_block2", "is_cube1_pushedTo_L1", "is_cube1_pushedTo_L2", "is_cylinder1_pushedTo_L1", "is_cylinder1_pushedTo_L2"]
    done_predicates: ['is_cube1_pushedTo_block2', 'is_cylinder1_pushedTo_block1']
    predicate_true_value: 1.0
    predicate_false_value: -1.0

    num_simple_states: 46


#    goal_pos: # This has to be validated in the fetch_moveit_test.py in fetch_openai_ros_example or something that tests this pos is possible
#      x: 2.0
#      y: 0.0