fetch: #namespace

    # Fetch Task Realated parameters
    n_actions: 14 #
    # # # linear.x, linear.y, angular.z, wrist_roll, wrist_flex, forearm_roll, elbow_flex, upperarm_roll, shoulder_lift, shoulder_pan, torso_lift, gripper_close
    n_observations: 1 # An image
    max_iterations: 20

    init_pos: # Use Fetch tuck arm joint values: http://docs.ros.org/indigo/api/fetch_teleop/html/tuck__arm_8py_source.html
      bellows_joint: 0.0
      head_pan_joint: 0.0
      head_tilt_joint: 0.0
      l_gripper_finger_joint: 0.0
      r_gripper_finger_joint: 0.0
      torso_lift_joint: 0.05
      shoulder_pan_joint: 0.0 #1.32
      shoulder_lift_joint: 0.0 #1.40
      upperarm_roll_joint: 0.0 #-0.2
      elbow_flex_joint: 1.5 #1.72
      forearm_roll_joint: 0.0
      wrist_flex_joint: -1.5 #1.66
      wrist_roll_joint: 0.0

    group_name: "arm" #"arm_with_torso"

    gripper_min_dist: 0.005
    gripper_max_dist: 0.1
    gripper_max_effort: 1.0

env:
    human_poses:
        lady_sitting: [2.6, -0.1, -0.4, 0.0, 0.0, -0.707, 0.707]
        boy_sitting: [0.5, 0.06, -0.28, 0.0, 0.0, 0.0, 1.0]

    target_region:
        white_mug: [[0.4, 1.1], [-1.3, -0.65], [0.36, 1.0]] #[[0.9, 1.1], [-1.2, -0.65], [0.36, 0.37]]
#        green_mug: []
        pink_mug: [[1.3, 2.0], [-0.83, -0.2], [0.36, 1.0]] #[[1.3, 1.93], [-0.83, -0.65], [0.36, 0.37]]

    target_position:
        white_mug: [1.0, -0.8, 0.365]
#        green_mug: []
        pink_mug: [1.4, -0.81, 0.365]

    reached_goal_reward: 1.0

    render: True # Use RGB observations
    merge_predicates_to_img: True # Expand image with one more dimension of predicates and padded zeros

    predicates:
        nearby:
            robot_near_LocA: ['fetch', 'white_mug', 2.5]
            robot_near_LocB: ['fetch', 'pink_mug', 2.5]
        within:
            is_white_mug_givenTo_boy: ['white_mug', [[0.5, 1.1], [-1.2, -0.65], [0.36, 1.0]]] #[[0.9, 1.1], [-1.2, -0.65], [0.36, 0.37]]]
            is_white_mug_givenTo_lady: ['white_mug', [[1.3, 1.93], [-0.83, -0.25], [0.36, 1.0]]] #[[1.3, 1.93], [-0.83, -0.65], [0.36, 0.37]]]
            is_pink_mug_givenTo_boy: ['pink_mug', [[0.5, 1.1], [-1.2, -0.65], [0.36, 1.0]]] #[[0.9, 1.1], [-1.2, -0.65], [0.36, 0.37]]]
            is_pink_mug_givenTo_lady: ['pink_mug', [[1.3, 1.93], [-0.83, -0.25], [0.36, 1.0]]] #[[1.3, 1.93], [-0.83, -0.65], [0.36, 0.37]]]
        grasped:
            is_get_white_mug: ['white_mug']
            is_get_pink_mug: ['pink_mug']

    predicates_list: ["robot_near_LocA", "robot_near_LocB", "is_white_mug_givenTo_boy", "is_white_mug_givenTo_lady", "is_pink_mug_givenTo_boy", "is_pink_mug_givenTo_lady", "is_get_white_mug", "is_get_pink_mug"]

    predicate_true_value: 1.0
    predicate_false_value: -1.0

#    goal_pos: # This has to be validated in the fetch_moveit_test.py in fetch_openai_ros_example or something that tests this pos is possible
#      x: 2.0
#      y: 0.0