wandb_version: 1

AUTO_ENTROPY_TUNING:
  desc: null
  value: true
BATCH_SIZE:
  desc: null
  value: 64
BIAS_IN_PREDICATE:
  desc: null
  value: true
BUFFER_SIZE:
  desc: null
  value: 200000
DELAYED_UPDATE:
  desc: null
  value: 2
DEMO_STARTS:
  desc: null
  value: 0
GAMMA:
  desc: null
  value: 0.99
IF_PRETRAIN_DEMO:
  desc: null
  value: true
INITIAL_RANDOM_ACTION:
  desc: null
  value: 5000
LAMBDA1:
  desc: null
  value: 1.0
LAMBDA2:
  desc: null
  value: 1.0e-05
LAMBDA3:
  desc: null
  value: 1.0
LOG_REG:
  desc: null
  value: 1.0e-08
LR_ACTOR:
  desc: null
  value: 0.0003
LR_ENTROPY:
  desc: null
  value: 0.0003
LR_EXPLAINER:
  desc: null
  value: 0.001
LR_QF1:
  desc: null
  value: 0.0003
LR_QF2:
  desc: null
  value: 0.0003
LR_VF:
  desc: null
  value: 0.0003
MANUAL_SHAPING:
  desc: null
  value: false
MAX_ENERGY:
  desc: null
  value: 50
MINI_BATCH_SIZE:
  desc: null
  value: 32
MULTIPLE_LEARN:
  desc: null
  value: 2
NEGATIVE_REWARD_ONLY:
  desc: null
  value: true
NETWORK:
  desc: null
  value:
    ACTOR_HIDDEN_SIZES:
    - 256
    - 256
    QF_HIDDEN_SIZES:
    - 256
    - 256
    VF_HIDDEN_SIZES:
    - 256
    - 256
NO_SHAPING:
  desc: null
  value: true
NUM_PREDICATES:
  desc: null
  value: 10
N_STEP:
  desc: null
  value: 5
ONE_HOT_PREDICATES:
  desc: null
  value: true
PER_ALPHA:
  desc: null
  value: 0.6
PER_BETA:
  desc: null
  value: 0.4
PER_EPS:
  desc: null
  value: 1.0e-06
PER_EPS_DEMO:
  desc: null
  value: 1.0
PRETRAIN_STEP:
  desc: null
  value: 100
PRINT_SHAPING:
  desc: null
  value: true
SE_GRAD_CLIP:
  desc: null
  value: 10
SHAPING_REWARD_CLIP:
  desc: null
  value:
  - -10
  - 10
SHAPING_REWARD_WEIGHT:
  desc: null
  value: 0.05
SIMPLE_STATES_SIZE:
  desc: null
  value: 46
STATES_WITH_PREDICATES:
  desc: null
  value: true
STATES_WITH_UTILITIES:
  desc: null
  value: true
TAU:
  desc: null
  value: 0.001
USE_HER:
  desc: null
  value: false
W_ENTROPY:
  desc: null
  value: 0.001
W_MEAN_REG:
  desc: null
  value: 0.001
W_PRE_ACTIVATION_REG:
  desc: null
  value: 0.0
W_STD_REG:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    cli_version: 0.9.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
algo:
  desc: null
  value: sesacfd_v2_nrs_s
avg_score_window:
  desc: null
  value: 100
demo_path:
  desc: null
  value: /data/datasets/SERL/Fetch/Push-v2
episode_num:
  desc: null
  value: 3000
load_from:
  desc: null
  value: null
log:
  desc: null
  value: true
max_episode_steps:
  desc: null
  value: 50
max_total_steps:
  desc: null
  value: 1000000.0
mode:
  desc: null
  value: DIRECT
record:
  desc: null
  value: false
render:
  desc: null
  value: false
render_after:
  desc: null
  value: 0
replay:
  desc: null
  value: false
robot_env_config:
  desc: null
  value: /home/yzha3/Research/kair_algorithms_draft_CoRL/scripts/../config/fetch_serl_push_env_2.yaml
save_period:
  desc: null
  value: 100
seed:
  desc: null
  value: 777
test:
  desc: null
  value: false
